# k3s/manifests/prod/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: flask-service
  namespace: prod
spec:
  selector:
    app: flask-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: NodePort